<?php


/**
 * quick check modules orders of execution (default all zero)
 * As e must be sure this one fires after our main lemon modules
 * see https://davidjguru.github.io/blog/drupal-tips-altering-order-of-execution-in-resources
 */


/**
 * @param $variables
 */
function module_general_pleiade_preprocess_page(&$variables) {
  $config = \Drupal::config('module_general_pleiade.settings');
  $colorTheme = $config->get('color_theme');
  $numero_telephone_support = $config->get('numero_telephone_support');
  $adresse_mail_support = $config->get('adresse_mail_support');
  // Add the JS library.
  $variables['#attached']['library'][] = 'module_general_pleiade/module_general_pleiade_js';
  // Add the CSS library.
  // $variables['#attached']['library'][] = 'module_general_pleiade/module_general_pleiade_css';

  $variables['#attached']['drupalSettings']['module_general_pleiade']['color_theme'] = $colorTheme;
  $variables['#attached']['drupalSettings']['module_general_pleiade']['numero_telephone_support'] = $numero_telephone_support;
  $variables['#attached']['drupalSettings']['module_general_pleiade']['adresse_mail_support'] = $adresse_mail_support;

}