<?php


/**
 * quick check modules orders of execution (default all zero)
 * As e must be sure this one fires after our main lemon modules
 * see https://davidjguru.github.io/blog/drupal-tips-altering-order-of-execution-in-resources
 */


/**
 * @param $variables
 */
function module_general_pleiade_preprocess_page(&$variables) {
  $config = \Drupal::config('module_general_pleiade.settings');
  $colorTheme = $config->get('color_theme');
  //$imageFooter = $config->get('image_footer');
  //$imageLeftSidebar = $config->get('image_left_sidebar');
  //$imageLeftSidebarReduced = $config->get('image_left_sidebar_reduced');
  if (!empty($imageFooter)) {
    $file = \Drupal\file\Entity\File::load($imageFooter[0]);
    if ($file) {
      $imageFooterUrl = file_create_url($file->getFileUri());
      // Use $logoPath as needed.
    }
  }
  if (!empty($imageLeftSidebar)) {
    $file = \Drupal\file\Entity\File::load($imageLeftSidebar[0]);
    if ($file) {
      $imageLeftSidebarUrl = file_create_url($file->getFileUri());
      // Use $logoPath as needed.
    }
  }
  if (!empty($imageLeftSidebarReduced)) {
    $file = \Drupal\file\Entity\File::load($imageLeftSidebarReduced[0]);
    if ($file) {
      $imageLeftSidebarReducedUrl = file_create_url($file->getFileUri());
      // Use $logoPath as needed.
    }
  }
  
  // Add the JS library.
  $variables['#attached']['library'][] = 'module_general_pleiade/module_general_pleiade_js';
  // Add the CSS library.
  // $variables['#attached']['library'][] = 'module_general_pleiade/module_general_pleiade_css';

  $variables['#attached']['drupalSettings']['module_general_pleiade']['color_theme'] = $colorTheme;
  //$variables['#attached']['drupalSettings']['module_general_pleiade']['image_footer'] = $imageFooterUrl;
  //$variables['#attached']['drupalSettings']['module_general_pleiade']['image_left_sidebar'] = $imageLeftSidebarUrl;
  //$variables['#attached']['drupalSettings']['module_general_pleiade']['image_left_sidebar_reduced'] = $imageLeftSidebarReducedUrl;
}