<?php


/**
 * quick check modules orders of execution (default all zero)
 * As e must be sure this one fires after our main lemon modules
 * see https://davidjguru.github.io/blog/drupal-tips-altering-order-of-execution-in-resources
 */

// $extension_config = \Drupal::configFactory()->getEditable('core.extension');
// $module_weight1 = $extension_config->get("module.api_lemon_pleiade"); 
// $module_weight2 = $extension_config->get("module.api_pastell_pleiade");
// var_dump($module_weight1 . ' et ' . $module_weight2);

/**
 * @param $variables
 */
function api_pastell_pleiade_preprocess_page(&$variables){


  $config = \Drupal::config('api_pastell_pleiade.settings');
  
  $field_pastell_url = $config->get('field_pastell_url');
  $field_pastell_documents_url = $config->get('field_pastell_documents_url');
  $field_pastell_entitites_url = $config->get('field_pastell_entities_url');
  $limit_documents = $config->get('field_pastell_limit_documents');
  $pastell_group = $config->get('field_pastell_ldap_group');
  $field_pastell_auth_method = $config->get('field_pastell_auth_method');

  //Add the JS library
  $variables['#attached']['library'][] = 'api_pastell_pleiade/api_pastell_pleiade_js';

  //Add the CSS library
  $variables['#attached']['library'][] = 'api_pastell_pleiade/api_pastell_pleiade_css';
  
  //Pass variables to Drupal.Settings
  $variables['#attached']['drupalSettings']['api_pastell_pleiade']['field_pastell_url'] = $field_pastell_url;
  $variables['#attached']['drupalSettings']['api_pastell_pleiade']['field_pastell_documents_url'] = $field_pastell_documents_url;
  $variables['#attached']['drupalSettings']['api_pastell_pleiade']['field_pastell_entities_url'] = $field_pastell_entitites_url;
  $variables['#attached']['drupalSettings']['api_pastell_pleiade']['field_pastell_ldap_group'] =  $pastell_group;
  $variables['#attached']['drupalSettings']['api_pastell_pleiade']['field_pastell_auth_method'] =  $field_pastell_auth_method;
}