<?php


/**
 * @param $variables
 */
function api_lemon_pleiade_preprocess_page(&$variables){

  $config = \Drupal::config('api_lemon_pleiade.settings');

  $field_lemon_url = $config->get('field_lemon_url');
  $field_lemon_myapps_url = $config->get('field_lemon_myapps_url');
  $field_lemon_sessioninfo_url = $config->get('field_lemon_sessioninfo_url');
  $field_lemon_totp_url = $config->get('field_lemon_totp_url');
  
  //Add the JS library
  $variables['#attached']['library'][] = 'api_lemon_pleiade/api_lemon_pleiade_js';
  //Pass variables to Drupal.Settings
  $variables['#attached']['drupalSettings']['api_lemon_pleiade']['field_lemon_url'] = $field_lemon_url;
  $variables['#attached']['drupalSettings']['api_lemon_pleiade']['field_lemon_myapps_url'] = $field_lemon_myapps_url;
  $variables['#attached']['drupalSettings']['api_lemon_pleiade']['field_lemon_sessioninfo_url'] = $field_lemon_sessioninfo_url;
  $variables['#attached']['drupalSettings']['api_lemon_pleiade']['field_lemon_totp_url'] = $field_lemon_totp_url;

} 