<?php

use Symfony\Component\HttpFoundation\Request;

/**
 * @param $variables
 */
function api_maarch_pleiade_preprocess_page(&$variables){


  //Add the JS library
  $variables['#attached']['library'][] = 'api_maarch_pleiade/api_maarch_pleiade_js';
   $variables['#attached']['library'][] = 'api_maarch_pleiade/api_maarch_pleiade_msg_js';

  //Add the CSS library
  $variables['#attached']['library'][] = 'api_maarch_pleiade/api_maarch_pleiade_css';
  
   $variables['#attached']['drupalSettings']['api_maarch_pleiade']['maarch_url'] = "/v1/api_maarch_pleiade/getMailsForAllBaskets";


}
function api_maarch_pleiade_preprocess_node__landing_page(&$variables) {
  $variables['#cache']['max-age'] = 0;
} 




