<?php

namespace Drupal\api_lemon_pleiade\Service;

use Drupal\Component\Serialization\Json;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;
use Psr\Http\Message\ResponseInterface;
use Drupal\Core\File\FileSystemInterface;
use Drupal\image\Entity\ImageStyle;

class LemonService implements LemonServiceInterface
{
    protected $settings_lemon;
    protected $client;

    public function __construct()
    {
        $moduleHandler = \Drupal::service('module_handler');
        $this->settings_lemon = $moduleHandler->moduleExists('api_lemon_pleiade') ? \Drupal::config('api_lemon_pleiade.settings') : NULL;

        $this->client = new Client([
            'http_errors' => false,
        ]);
    }

    /**
     * Fetches apps and recursively optimizes all 'AppLogo' icons found in the JSON.
     */
    public function searchMyApps()
    {
        $endpoint = $this->settings_lemon->get('field_lemon_myapps_url');
        $data = $this->executeCurl($endpoint, "GET", [], $this->settings_lemon->get('field_lemon_url'));

        if ($data && is_array($data)) {
            $this->optimizeIconsRecursively($data);
        }

        return $data;
    }

    /**
     * Recursively traverses the JSON array to find and process 'AppLogo' fields.
     */
    protected function optimizeIconsRecursively(&$item) {
        if (!is_array($item)) {
            return;
        }

        foreach ($item as $key => &$value) {
            // If we find the 'AppLogo' key with a URL, we process it.
            if ($key === 'AppLogo' && is_string($value) && strpos($value, 'http') === 0) {
                $value = $this->processExternalIcon($value);
            } 
            // Otherwise, keep digging deeper into the nested structure.
            elseif (is_array($value)) {
                $this->optimizeIconsRecursively($value);
            }
        }
    }

    /**
     * Downloads an external icon and processes it via ImageMagick Image Styles.
     */
    protected function processExternalIcon($external_url) {
        if (empty($external_url)) return $external_url;

        $image_style = ImageStyle::load('app_icon');
        $directory = 'public://app_icons';
        // Create a unique filename based on the URL hash.
        $filename = 'icon_' . md5($external_url) . '.png';
        $destination = $directory . '/' . $filename;

        $storage = \Drupal::entityTypeManager()->getStorage('file');
        $existing_files = $storage->loadByProperties(['uri' => $destination]);

        $file = null;

        if (empty($existing_files)) {
            try {
                // Fetch the external image.
                $imageData = @file_get_contents($external_url);
                if ($imageData) {
                    \Drupal::service('file_system')->prepareDirectory($directory, FileSystemInterface::CREATE_DIRECTORY);
                    $file = \Drupal::service('file.repository')->writeData($imageData, $destination, FileSystemInterface::EXISTS_REPLACE);
                }
            } catch (\Exception $e) {
                \Drupal::logger('api_lemon_pleiade')->error("ImageMagick processing failed for icon: " . $e->getMessage());
            }
        } else {
            $file = reset($existing_files);
        }

        // Return the URL for the 32x32 WebP version generated by ImageMagick.
        if ($file && $image_style) {
            return $image_style->buildUrl($file->getFileUri());
        }

        return $external_url;
    }

    public function searchMySession()
    {
        $endpoint = $this->settings_lemon->get('field_lemon_sessioninfo_url');
        return $this->executeCurl($endpoint, "GET", [], $this->settings_lemon->get('field_lemon_url'));
    }

    public function executeCurl($endpoint, $method, $inputs, $api)
    {
        $url = rtrim($api, '/') . "/" . ltrim($endpoint, '/');
        $options = [
            'headers' => [
                'Content-Type' => 'application/json',
                'Cookie' => 'llnglanguage=fr; lemonldap=' . ($_COOKIE['lemonldap'] ?? ''),
            ],
        ];

        if (!empty($inputs)) {
            if ($method === 'GET') {
                $url .= '?' . http_build_query($inputs);
            } else {
                $options['json'] = $inputs;
            }
        }

        try {
            $response = $this->client->request($method, $url, $options);
            return $this->handleResponse($response, $method, $url, $options);
        } catch (RequestException $e) {
            $this->logError($method, $url, $options, $e->getMessage());
            return null;
        }
    }

    protected function handleResponse(ResponseInterface $response, $method, $url, $options)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();

        if ($status < 400) {
            return Json::decode($body);
        } else {
            $this->logError($method, $url, $options, "Status $status", $body);
            return null;
        }
    }

    protected function logError($method, $url, $options, $error, $responseBody = null)
    {
        \Drupal::logger('api_lemon_pleiade')->error(
            "❌ Error {method} {url} - {error}",
            [
                'method' => $method,
                'url' => $url,
                'error' => $error,
                'options' => $options,
                'response' => $responseBody,
            ]
        );
    }

    public static function arrayKeyfirst($array)
    {
        return function_exists('array_key_first') ? array_key_first($array) : key($array);
    }

    public function refresh_session()
    {
        $url = "https://portail.sitiv.fr/refresh";
        $options = [
            'headers' => [
                'Cookie' => 'llnglanguage=fr; lemonldap=' . ($_COOKIE['lemonldap'] ?? ''),
            ],
        ];

        try {
            $response = $this->client->request("GET", $url, $options);
            return $this->handleResponse($response, "GET", $url, $options) !== null;
        } catch (RequestException $e) {
            $this->logError("GET", $url, $options, $e->getMessage());
            return false;
        }
    }
}