<?php


use Drupal\Core\Url;





/**
 * Implements hook_install().
 */
function api_watcha_pleiade_install() {
    // Ensures the hooks contained in your module will be executed after the originals.
    // e.g. the hook menu_ui_form_node_form_alter()
    // Note: Weight for uninstalled modules can't be changed. 
    module_set_weight('api_watcha_pleiade', 101);

    // Warn user about config
    $messenger = \Drupal::messenger();
    $messenger->addStatus(t('Pour faire fonctionner une instance de watcha avec Pléiade, vous devez <a href=":watcha_conf_url">configurer le module</a>.', [
      ':watcha_conf_url' => Url::fromUri('internal:/admin/config/api_watcha_pleiade/settings')->toString(),
    ]));
  
  }

