<?php


/**
 * quick check modules orders of execution (default all zero)
 * As e must be sure this one fires after our main lemon modules
 * see https://davidjguru.github.io/blog/drupal-tips-altering-order-of-execution-in-resources
 */


/**
 * @param $variables
 */
function api_user_pleiade_preprocess_page(&$variables){

  $config = \Drupal::config('api_user_pleiade.settings');
  $have_chatbot = $config->get('have_chatbot');
  $apiKey = $config->get('apiKey');
  $bot_id = $config->get('bot_id');
  

  //Add the JS library
  $variables['#attached']['library'][] = 'api_user_pleiade/api_user_pleiade_js';
  //Add the CSS library
  $variables['#attached']['library'][] = 'api_user_pleiade/api_user_pleiade_css';

  $variables['#attached']['drupalSettings']['api_user_pleiade']['have_chatbot'] = $have_chatbot;
  $variables['#attached']['drupalSettings']['api_user_pleiade']['apiKey'] = $apiKey;
  $variables['#attached']['drupalSettings']['api_user_pleiade']['bot_id'] = $bot_id;
  
  $current_user = \Drupal::currentUser();

  // Get the user entity.
  $user = \Drupal\user\Entity\User::load($current_user->id());
  
  // Initialize an array to store user information.
  $user_info = array();
  
  // Check if the user entity exists.
  if ($user) {
      // Get all user fields and their values.
      $fields = $user->getFields();
  
      // Iterate through each field.
      foreach ($fields as $field_name => $field) {
          // Get the field value.
          $field_value = $field->getValue();
  
          // Store the field name and value in the user info array.
          $user_info[$field_name] = $field_value;
      }
      if($user_info){
      $variables['#attached']['drupalSettings']['api_user_pleiade']['user_info'] = $user_info;
      }
  }

}
