<?php


/**
 * quick check modules orders of execution (default all zero)
 * As e must be sure this one fires after our main lemon modules
 * see https://davidjguru.github.io/blog/drupal-tips-altering-order-of-execution-in-resources
 */


/**
 * @param $variables
 */
function api_user_pleiade_preprocess_page(&$variables){

  $config = \Drupal::config('api_user_pleiade.settings');
  $field_user = $config->get('field_user');

  //Add the JS library
  $variables['#attached']['library'][] = 'api_user_pleiade/api_user_pleiade_js';
  //Add the CSS library
  $variables['#attached']['library'][] = 'api_user_pleiade/api_user_pleiade_css';

  $variables['#attached']['drupalSettings']['api_user_pleiade']['field_user'] = $field_user;

}