<?php

/**
 * Implements hook_system_info_alter().
 */
function accessibility_tools_system_info_alter(&$info, $file, $type)
{
  // Ajoute une nouvelle région de mise en page pour les blocs.
  $info['regions']['accessibility_tools'] = ('Zone pour l\'Accessibilité');
}

function accessibility_tools_preprocess_page(&$variables)
{
  //Add the JS library
  $variables['#attached']['library'][] = 'accessibility_tools/accessibility_tools_js';

  //Add the CSS library
  $variables['#attached']['library'][] = 'accessibility_tools/accessibility_tools_css';
}



/**
 * Implements hook_form_FORM_ID_alter() for user edit form.
 */
/**
 * Implements hook_form_FORM_ID_alter() for user edit form.
 */

function accessibility_tools_page_attachments(array &$attachments)
{

  $current_user = \Drupal::currentUser();

  // Only apply for authenticated users
  if ($current_user->isAuthenticated()) {
    $route_match = \Drupal::routeMatch();
    $route_name = $route_match->getRouteName();

    // Skip for admin pages (like admin/* or system routes)
    if (strpos($route_name, 'admin') === 0 || strpos($route_name, 'system.') === 0) {
      return;
    }

    $account = \Drupal\user\Entity\User::load($current_user->id());
    $is_menu = $account->get("field_ismenuopened")->value ?? '';
    $js_code = <<<JS
  ( function() {
    
      localStorage.setItem("menuOpen_", "$is_menu");
 
  })();
JS;

    $attachments['#attached']['html_head'][] = [
      [
        '#tag' => 'script',
        '#value' => $js_code,
      ],

      'user_fields_localstorage',
    ];
  }
}
