<?php


/**
 * quick check modules orders of execution (default all zero)
 * As e must be sure this one fires after our main lemon modules
 * see https://davidjguru.github.io/blog/drupal-tips-altering-order-of-execution-in-resources
 */
/**
 * @param $variables
 */
function datatable_pleiade_preprocess_page(&$variables) {

  // Add the JS library.
  $variables['#attached']['library'][] = 'datatable_pleiade/datatable_pleiade_js';
  // Add the CSS library.
  $variables['#attached']['library'][] = 'datatable_pleiade/datatable_pleiade_css';

}