<?php

/**
 * @param $variables
 */

function message_module_pleiade_preprocess_page(&$variables){
// Add the CSS library
  $variables['#attached']['library'][] = 'message_module_pleiade/message_module_pleiade_css';

// Add the JS library
  $variables['#attached']['library'][] = 'message_module_pleiade/message_module_pleiade_js';
  
// Config form values
$config = \Drupal::config('message_module_pleiade.settings');
  $variables['#attached']['drupalSettings']['message_module_pleiade']['message_actif'] = $config->get('message_actif');;
  $variables['#attached']['drupalSettings']['message_module_pleiade']['message_a_afficher'] = $config->get('message_a_afficher');;
  $variables['#attached']['drupalSettings']['message_module_pleiade']['gravite_du_message'] = $config->get('gravite_du_message');
}