<?php


use Drupal\Core\Url;



/**
 * Implements hook_install().
 */
function api_ciril_pleiade_install() {
    // Ensures the hooks contained in your module will be executed after the originals.
    // e.g. the hook menu_ui_form_node_form_alter()
    // Note: Weight for uninstalled modules can't be changed. 
    module_set_weight('api_ciril_pleiade', 101);

    // Warn user about config
    $messenger = \Drupal::messenger();
    $messenger->addStatus(t('Pour faire fonctionner une instance de ciril avec Pléiade, vous devez <a href=":ciril_conf_url">configurer le module</a>.', [
      ':ciril_conf_url' => Url::fromUri('internal:/admin/config/api_ciril_pleiade/settings')->toString(),
    ]));
  
  }

