<?php


/**
 * quick check modules orders of execution (default all zero)
 * As e must be sure this one fires after our main lemon modules
 * see https://davidjguru.github.io/blog/drupal-tips-altering-order-of-execution-in-resources
 */


/**
 * @param $variables
 */
function module_postit_pleiade_preprocess_page(&$variables){
$variables['#attached']['library'][] = 'module_postit_pleiade/module_postit_pleiade_js';
$variables['#attached']['library'][] = 'module_postit_pleiade/module_postit_pleiade_css';

}
